version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: casino_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casino_db
      MYSQL_USER: casino_user
      MYSQL_PASSWORD: casino_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
